### ISSUE TITLE
[安全] 手动下棋时造成的代码泄露和 XSS 注入

### ISSUE THREAD

**Issue by fyc09** [Bit-Mountain/issues#1]
*我提议建仓库，我先提一个 Issue*

在井字棋、五子棋等游戏中，**手动下棋** 时，对方的代码是在浏览器本地执行的。在这过程中，用户可以窃取对方的代码，这不利于比赛的公平。
即使是手动下棋也应该在服务端运行代码。

**Comment by fyc09** [comment]
我已经在五子棋和井字棋中成功拿到了第一名的代码

*当然，我没有把它当成我自己的代码提交，井字棋第一名的代码是我自己写的。*

**Comment by Littlefean** [comment]
这个是我正在考虑到问题，我会考虑改成每下一步棋就在服务器端执行一次，这样就不会在本地执行代码了。

但这样就又有了一个新的问题，以后如果出了“坦克大战”这样的很快速的游戏模式，可能还是要放在浏览器上运行，这样的话就需要对浏览器上的代码进行加密，但加密方法我目前还没有测试成功。

我加了一些其他的代码混淆，让搜索'action (board)'的时候会出现更多的结果，以此来混淆。但还没有起到什么效果。

**Comment by fyc09** [comment]
WebSocket 延迟没有那么高，即使做快速的游戏应该不用太担心。

代码混淆加密的实现成本，绝对会比将代码移到服务端执行大。因为对战的代码通常不会很长，而且用户可以自行提交经过特别处理的代码（例如打日志），混淆加密很容易破解。

我还发现把代码在浏览器端执行可以进行 **XSS 注入**，这点非常危险。

**Comment by zty012** [comment]
![screenshots](https://github.com/Bit-Mountain/issues/assets/89395757/36f4d70c-605b-488a-b2fc-a9bd9d055d25)

↑这里有个gif，加载可能有点慢

**Comment by fyc09** [comment]
ZhuWuyin 的井字棋代码和之前的第一名 Suger51243 的代码完全一样。请尽快处理！

**Comment by fyc09** [comment]
看来以后安全问题不能公开提了

**Comment by Littlefean** [comment]
现在暂时关闭了手动试下的功能，防止更多的代码泄漏。正在维护

**Comment by zty012** [comment]
已修复
