### ISSUE TITLE
[BUG] 绝杀出现判断错误

### ISSUE THREAD

**Issue by fyc09** [Bit-Mountain/issues#3]
![image](https://github.com/Bit-Mountain/issues/assets/78291982/a218ad57-921c-46d8-83bd-9650573157be)
即使我被绝杀了，但系统依然判我胜。如图，我（diolam）胜 1，败 0。

**Comment by Littlefean** [comment]
这个模式更新了，大波从消耗12能量改成了消耗7能量，并且只能打掉一条命了。

我在更新之前发现了一个bug，本来是消耗12能量的，但是我写的之前是7能量，不知道是不是因为这个能量数值的问题导致的bug，现在已经修改了，不知道还会不会有这个bug，可以再试一下

**Comment by fyc09** [comment]
现在好了
